### ISSUE TITLE
El componente profile card le faltan los media queries

### ISSUE THREAD

**Issue by SanArGuz** [Cohort-4-Team-Diego/React-Perfiles#8]
en modo tablet genera una barra blanca a la derecha debido a que los componentes tienen un paddin fijo

**Comment by Ulzahk** [comment]
Con los cambios realizados hoy se logro solucionar la linea blanca, pero ahora faltan los espacios entre tarjetas.

**Comment by Ulzahk** [comment]
Esperando aprobación de @OscarPay

**Comment by Ulzahk** [comment]
Listo completado
